name: release

on:
  push:
    tags:
      - '*'

jobs:
  build_release:
    name: Package and release extension
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: npm
        run: npm install
      - name: package
        uses: lannonbr/vsce-action@3.0.0
        with:
           args: "package"
      - run: echo "name=$(ls | grep vsix | sort | tail -n 1)" >> $GITHUB_OUTPUT
        id: identify-package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{steps.identify-package.outputs.name}}